-- oracle create table brang with column 
-- 1. KODE_BARANG NOT NULL CHAR 6
-- 2. NAMA_BARANG VARCHAR2 20
-- 3. SATUAN_BARANG VARCHAR2 10
-- KODE BARANG PRIMARY KEY

CREATE TABLE barang(
    KODE_BARANG CHAR(6) NOT NULL,
    NAMA_BARANG VARCHAR2(20),
    SATUAN_BARANG VARCHAR2(10),
    PRIMARY KEY(KODE_BARANG)
);

-- Tambahkan sebuah kolom : stok_barang (int), sebagai kolom terakhir ! 

alter table BARANG add stok_barang int;

-- create table with name SUPLIER and column
-- 1. KODE_SUPLIER NOT NULL CHAR 6
-- 2. NAMA_SUPLIER VARCHAR2 30
-- 3. ALAMAT_SUPLIER VARCHAR2 50
-- KODE_SUPLIER PRIMARY KEY

create table SUPLIER(
    KODE_SUPLIER CHAR(6) NOT NULL,
    NAMA_SUPLIER VARCHAR2(30),
    ALAMAT_SUPLIER VARCHAR2(50),
    PRIMARY KEY(KODE_SUPLIER)
);

-- Ubahlah agar tipe data dari field alamat_suplier dari varchar2(50) menjadi char(40)

alter table SUPLIER modify ALAMAT_SUPLIER char(40);

-- create table customer and add column 
-- 1. KODE_CUSTOMER NOT NULL CHAR 6
-- 2. NAMA_CUSTOMER VARCHAR2 30
-- 3. ALAMAT_CUSTOMER VARCHAR2 50
-- KODE_CUSTOMER PRIMARY KEY

create table customer(
    KODE_CUSTOMER CHAR(6) NOT NULL,
    NAMA_CUSTOMER VARCHAR2(30),
    ALAMAT_CUSTOMER VARCHAR2(50),
    PRIMARY KEY(KODE_CUSTOMER)
);

-- crete table PASOK and add column
-- 1. KODE_PASOK NOT NULL CHAR 6
-- 2. KODE_BARANG NOT NULL CHAR 6
-- 3. KODE_SUPLIER NOT NULL CHAR 6
-- 4. JUMLAH_PASOK NUMBER(38)
-- KODE_PASOK PRIMARY KEY
-- KODE_BARANG FOREIGN KEY REFERENCES BARANG
-- KODE_SUPLIER FOREIGN KEY REFERENCES SUPLIER

CREATE TABLE PASOK(
    KODE_PASOK CHAR(6) NOT NULL,
    KODE_BARANG CHAR(6) NOT NULL,
    KODE_SUPLIER CHAR(6) NOT NULL,
    JUMLAH_PASOK NUMBER(38),
    PRIMARY KEY(KODE_PASOK),
    FOREIGN KEY(KODE_BARANG) REFERENCES BARANG(KODE_BARANG),
    FOREIGN KEY(KODE_SUPLIER) REFERENCES SUPLIER(KODE_SUPLIER)
);